fix: run-deposit env.

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -308,6 +308,8 @@ jobs:
 
     env:
       INFO_LOG_FILE: ${{ github.workspace }}/test-logs/debug/debug-all-features-test.log
+      BQR_ALIAS: bitcoin-cli -regtest -rpcport=20443 -rpcuser=admin -rpcpassword=admin
+      BITCOIN_RPC_URL: http://127.0.0.1:20443
 
     steps:
       - name: Collect Workflow Telemetry
@@ -346,10 +348,12 @@ jobs:
           echo $! > docker_compose_pid.txt
           sleep 100
           cd core
-          export BQR_ALIAS="bitcoin-cli -regtest -rpcport=20443 -rpcuser=admin -rpcpassword=admin"
-          export BITCOIN_RPC_URL="http://127.0.0.1:20443"
           for i in {1..30}; do
             timeout 20 ../scripts/run-deposit.sh && break
             echo "run-deposit.sh failed, retrying in 10 seconds ($i/30)..."
             sleep 10
+            if [ "$i" -eq 30 ]; then
+              echo "run-deposit.sh failed after 30 attempts"
+              exit 1
+            fi
           done
